name: Deploy Next.js to S3 and invalidate CloudFront

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. 저장소를 체크아웃합니다.
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Node.js 18.x 버전을 설정합니다.
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # 3. 프로젝트 의존성을 설치합니다.
      - name: Install dependencies
        run: yarn install

      # 4. Next.js 프로젝트를 빌드합니다.
      - name: Build
        run: yarn run build

      # 5. AWS 자격 증명을 구성합니다.
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # 6. 빌드된 파일을 S3 버킷에 동기화합니다.
      - name: Deploy to S3
        run: |
          aws s3 sync out/ s3://${{ secrets.S3_BUCKET_NAME }} --delete

      # 7. CloudFront 캐시를 무효화합니다.
      - name: Invalidate CloudFront cache
        run: |
          aws cloudfront create-invalidation --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} --paths "/*"
